apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h8lhc70hk-nodejs 
  janus-idp.io/tekton: h8lhc70hk-nodejs
  backstage.io/kubernetes-id: h8lhc70hk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h8lhc70hk-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  