apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h8lhc70hk-nodejs
  janus-idp.io/tekton: h8lhc70hk-nodejs
  backstage.io/kubernetes-id: h8lhc70hk-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h8lhc70hk-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
